make: fix slave commands parameters

diff --git a/bar/test/Makefile.in b/bar/test/Makefile.in
--- a/bar/test/Makefile.in
+++ b/bar/test/Makefile.in
@@ -2485,6 +2485,484 @@ test_misc-valgrind: \
   $(TEST_BAR_VALGRIND)
 	@$(MAKE) TEST_BAR_PREFIX="$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) --leak-check=full --show-leak-kinds=all" TEST_BAR="$(TEST_BAR_VALGRIND)" test_misc
 
+# ----------------------------------------------------------------------------
+
+# valgrind checks
+.PHONY: memcheck
+memcheck: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(MAKE) \
+          VALGRIND_OPTIONS="--leak-check=summary" \
+          $(if $(CHECK),\
+            memcheck$(CHECK),\
+            memcheck1 memcheck2a memcheck2b memcheck2c memcheck2d memcheck2e memcheck3 memcheck4 memcheck5 memcheck6 memcheck7 memcheck8 \
+           )
+
+.PHONY: memcheck_extended
+memcheck_extended: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(MAKE) \
+          VALGRIND_OPTIONS="--leak-check=full" \
+            $(if $(CHECK),\
+              memcheck$(CHECK),\
+              memcheck1 memcheck2a memcheck2b memcheck2c memcheck2d memcheck2e memcheck3 memcheck4 memcheck5 memcheck6 memcheck7 memcheck8 \
+             )
+
+.PHONY: memcheck1 memcheck2 memcheck2a memcheck2b memcheck2c memcheck2d memcheck2e memcheck3 memcheck4 memcheck5 memcheck6 memcheck7 memcheck8
+memcheck1: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) --help >/dev/null
+memcheck2: \
+  memcheck2a \
+  memcheck2b \
+  memcheck2c \
+  memcheck2d \
+  memcheck2e
+memcheck2a: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --overwrite-archive-files >/dev/null
+memcheck2b: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --compress-algorithm=bzip9 --overwrite-archive-files >/dev/null
+memcheck2c: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --crypt-algorithm=AES256 --crypt-password=$(TEST_PASSWORD_CRYPT) --overwrite-archive-files >/dev/null
+memcheck2d: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --compress-algorithm=none --crypt-algorithm=AES256 --crypt-password=$(TEST_PASSWORD_CRYPT) --crypt-type=asymmetric --crypt-public-key=$(CURDIR)/$(TEST_KEY_CRYPT_PUBLIC) --crypt-private-key=$(CURDIR)/$(TEST_KEY_CRYPT_PRIVATE) --signature-public-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PUBLIC) --signature-private-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PRIVATE) --overwrite-archive-files >/dev/null
+memcheck2e: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -c intermediate/test-###.bar $(TEST_FILES) $(BAR_OPTIONS) --archive-part-size=100000 --overwrite-archive-files >/dev/null
+memcheck2f: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --overwrite-archive-files --dry-run >/dev/null
+memcheck3:  \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --overwrite-archive-files >/dev/null
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -l intermediate/test*.bar $(BAR_OPTIONS) >/dev/null
+memcheck4: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --overwrite-archive-files >/dev/null
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -t intermediate/test*.bar $(BAR_OPTIONS) >/dev/null
+memcheck5: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --overwrite-archive-files >/dev/null
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -d intermediate/test*.bar $(BAR_OPTIONS) >/dev/null
+memcheck6: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --overwrite-archive-files >/dev/null
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) -x intermediate/test*.bar $(BAR_OPTIONS) --destination intermediate/restore >/dev/null
+memcheck7: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(TEST_BAR_VALGRIND) -c intermediate/test.bar $(TEST_FILES) $(BAR_OPTIONS) --overwrite-archive-files >/dev/null
+	-$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) dvd:///dev/dvd $(BAR_OPTIONS) >/dev/null
+	-$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) dvd:///dev/dvd: $(BAR_OPTIONS) >/dev/null
+memcheck8: \
+  $(TEST_BAR_VALGRIND) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(VALGRIND) --tool=memcheck $(VALGRIND_FLAGS) \
+          --log-file=valgrind.log \
+          --leak-check=full \
+          --leak-resolution=high \
+          --track-fds=yes \
+          --suppressions=valgrind.supp \
+          $(VALGRIND_OPTIONS) \
+          $(TEST_BAR_VALGRIND) \
+            --daemon \
+            --no-detach \
+            --no-default-config \
+            --jobs-directory=jobs \
+            --server-ca-file=bar-ca.pem \
+            --server-cert-file=bar-server-cert.pem \
+            --server-key-file=bar-server-key.pem \
+            --server-port=$(SERVER_PORT) \
+            --server-tls-port=$(SERVER_SSL_PORT) \
+            --debug-server &
+	$(SLEEP) 30
+	$(ECHO) '1 VERSION' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 JOB_LIST' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 DEVICE_LIST' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 FILE_LIST storageDirectory=/tmp'| $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 PASSWORDS_CLEAR' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 INDEX_STORAGE_LIST maxCount=10 indexState=* indexMode=* pattern=x'| $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 DEBUG_PRINT_STATISTICS' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 DEBUG_PRINT_MEMORY_INFO' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 DEBUG_DUMP_MEMORY_INFO' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) 'UNKNOWN' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 UNKNOWN' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+	$(ECHO) '1 QUIT' | $(NETCAT) $(TEST_HOST) $(SERVER_PORT)
+
+#valgrind --tool=callgrind ./bar@EXEEXT@ -c test2.bar -o -z xdelta9 --delta-source=test1.bar bar
+#valgrind --tool=cachegrind ./bar@EXEEXT@ -c test2.bar -o -z xdelta9 --delta-source=test1.bar bar
+
+# ----------------------------------------------------------------------------
+
+# testcode runs:
+#   1A+2+3+4: full+list+diff+extract
+#   1B+2+3+4: differentiell+list+diff+extract
+#   1C+2+3+4: incremental+list+diff+extract
+
+TESTCODE_COMMAND1A=$(TEST_BAR_DEBUG) \
+                     --compress-algorithm=lzma9 \
+                     --crypt-algorithm=AES256 \
+                     --crypt-password=$(TEST_PASSWORD_CRYPT) \
+                     --crypt-type=asymmetric \
+                     --crypt-public-key=$(CURDIR)/$(TEST_KEY_CRYPT_PUBLIC) \
+                     --crypt-private-key=$(CURDIR)/$(TEST_KEY_CRYPT_PRIVATE) \
+                     --signature-public-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PUBLIC) \
+                     --signature-private-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PRIVATE) \
+                     --archive-part-size=100K \
+                     --overwrite-archive-files \
+                     --full \
+                     --log-post-command='true' \
+                     -c intermediate/test-\#\#\#.bar $(TEST_DATA_DIR)/data
+TESTCODE_COMMAND1B=$(TEST_BAR_DEBUG) \
+                     --compress-algorithm=lzma9 \
+                     --crypt-algorithm=AES256 \
+                     --crypt-password=$(TEST_PASSWORD_CRYPT) \
+                     --crypt-type=asymmetric \
+                     --crypt-public-key=$(CURDIR)/$(TEST_KEY_CRYPT_PUBLIC) \
+                     --crypt-private-key=$(CURDIR)/$(TEST_KEY_CRYPT_PRIVATE) \
+                     --signature-public-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PUBLIC) \
+                     --signature-private-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PRIVATE) \
+                     --archive-part-size=100K \
+                     --overwrite-archive-files \
+                     --differential \
+                     --incremental-list-file=intermediate/test.bid \
+                     --log-post-command='true' \
+                     -c intermediate/test-\#\#\#.bar $(TEST_DATA_DIR)/data
+TESTCODE_COMMAND1C=$(TEST_BAR_DEBUG) \
+                     --compress-algorithm=lzma9 \
+                     --crypt-algorithm=AES256 \
+                     --crypt-password=$(TEST_PASSWORD_CRYPT) \
+                     --crypt-type=asymmetric \
+                     --crypt-public-key=$(CURDIR)/$(TEST_KEY_CRYPT_PUBLIC) \
+                     --crypt-private-key=$(CURDIR)/$(TEST_KEY_CRYPT_PRIVATE) \
+                     --signature-public-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PUBLIC) \
+                     --signature-private-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PRIVATE) \
+                     --archive-part-size=100K \
+                     --overwrite-archive-files \
+                     --incremental \
+                     --incremental-list-file=intermediate/test.bid \
+                     --log-post-command='true' \
+                     -c intermediate/test-\#\#\#.bar $(TEST_DATA_DIR)/data
+TESTCODE_COMMAND2=$(TEST_BAR_DEBUG) \
+                     --crypt-password=$(TEST_PASSWORD_CRYPT) \
+                     --crypt-public-key=$(CURDIR)/$(TEST_KEY_CRYPT_PUBLIC) \
+                     --crypt-private-key=$(CURDIR)/$(TEST_KEY_CRYPT_PRIVATE) \
+                     --signature-public-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PUBLIC) \
+                     --signature-private-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PRIVATE) \
+                     -l intermediate/test-*.bar
+TESTCODE_COMMAND3=$(TEST_BAR_DEBUG) \
+                     --crypt-password=$(TEST_PASSWORD_CRYPT) \
+                     --crypt-public-key=$(CURDIR)/$(TEST_KEY_CRYPT_PUBLIC) \
+                     --crypt-private-key=$(CURDIR)/$(TEST_KEY_CRYPT_PRIVATE) \
+                     --signature-public-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PUBLIC) \
+                     --signature-private-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PRIVATE) \
+                     -d intermediate/test-*.bar
+TESTCODE_COMMAND4=$(TEST_BAR_DEBUG) \
+                     --crypt-password=$(TEST_PASSWORD_CRYPT) \
+                     --crypt-public-key=$(CURDIR)/$(TEST_KEY_CRYPT_PUBLIC) \
+                     --crypt-private-key=$(CURDIR)/$(TEST_KEY_CRYPT_PRIVATE) \
+                     --signature-public-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PUBLIC) \
+                     --signature-private-key=$(CURDIR)/$(TEST_KEY_SIGNATURE_PRIVATE) \
+                     --destination=intermediate/restore \
+                     -x intermediate/test-*.bar
+
+TESTCODE_COMMANDS = \
+  TESTCODE_COMMAND1A \
+  TESTCODE_COMMAND1B \
+  TESTCODE_COMMAND1C \
+  TESTCODE_COMMAND2 \
+  TESTCODE_COMMAND3 \
+  TESTCODE_COMMAND4 \
+
+# call functionTestcode(command)
+functionTestcode = \
+ if test $$rc -ne $(TESTCODE_EXITCODE); then \
+   TESTCODE_LIST=testcode.list TESTCODE_NAME=testcode.name TESTCODE_DONE=testcode.done \
+     $($1) >/dev/null; \
+   rc=$$?; \
+   if test $$rc -ne $(TESTCODE_EXITCODE); then \
+     $(ECHO) "Test code fail $1 (exitcode: $$rc):"; \
+     $(ECHO) "TESTCODE=$(if $(testcode),$(testcode),`$(CAT) testcode.name 2>/dev/null`) $($1)"; \
+   fi; \
+ fi
+
+# helper function to execute test code
+# call functionTestcodeA
+# call functionTestcodeB
+# call functionTestcodeC
+functionTestcodeA = \
+  ( \
+   rc=0; \
+   \
+   $(call functionTestcode,TESTCODE_COMMAND1A); \
+   $(call functionTestcode,TESTCODE_COMMAND2); \
+   $(call functionTestcode,TESTCODE_COMMAND3); \
+   $(call functionTestcode,TESTCODE_COMMAND4); \
+   \
+   exit $$rc; \
+  )
+
+functionTestcodeB = \
+  ( \
+   rc=0; \
+   \
+   $(call functionTestcode,TESTCODE_COMMAND1B); \
+   $(call functionTestcode,TESTCODE_COMMAND2); \
+   $(call functionTestcode,TESTCODE_COMMAND3); \
+   $(call functionTestcode,TESTCODE_COMMAND4); \
+   \
+   if test -z "$(TESTCODE)" -a -z "`$(CAT) testcode.name 2>/dev/null`"; then \
+     $(ECHO) "ERROR: No more testcode executed!"; \
+     $(ECHO) ""; \
+     $(ECHO) "Available and not executed testcode:"; \
+     $(MAKE) --quiet testcode_diff; \
+   fi; \
+   \
+   exit $$rc; \
+  )
+
+functionTestcodeC = \
+  ( \
+   rc=0; \
+   \
+   $(call functionTestcode,TESTCODE_COMMAND1C); \
+   $(call functionTestcode,TESTCODE_COMMAND2); \
+   $(call functionTestcode,TESTCODE_COMMAND3); \
+   $(call functionTestcode,TESTCODE_COMMAND4); \
+   \
+   if test -z "$(TESTCODE)" -a -z "`$(CAT) testcode.name 2>/dev/null`"; then \
+     $(ECHO) "ERROR: No more testcode executed!"; \
+     $(ECHO) ""; \
+     $(ECHO) "Available and not executed testcode:"; \
+     $(MAKE) --quiet testcode_diff; \
+   fi; \
+   \
+   exit $$rc; \
+  )
+
+.PHONY: testcode_clean testcode_init testcode_all testcode testcodex testcode_list testcode_diff
+
+testcode_clean:
+	$(RMF) testcode.list testcode.skip testcode.name testcode.done
+
+testcode_init: \
+  $(TEST_BAR_DEBUG) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	$(ECHO_NO_LF) >testcode.list
+	$(ECHO_NO_LF) >testcode.done
+	for z in $(TESTCODE_SKIP); do $(ECHO) $$s; done >testcode.skip
+	$(foreach z,$(TESTCODE_COMMANDS),TESTCODE_LIST=testcode.list $($z) >/dev/null;)
+
+testcode_all: \
+  $(TEST_BAR_DEBUG) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	rc=$(TESTCODE_EXITCODE); \
+        while test $$rc -eq $(TESTCODE_EXITCODE); do \
+          rc=0; \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
+            $(call functionTestcodeA) 1>/dev/null 2>/dev/null; \
+            rc=$$?; \
+          fi; \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
+            $(call functionTestcodeB); \
+            rc=$$?; \
+          fi; \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
+            $(call functionTestcodeC); \
+            rc=$$?; \
+          fi; \
+        done
+
+testcode: \
+  $(TEST_BAR_DEBUG) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+          rc=0; \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
+            $(call functionTestcodeA); \
+            rc=$$?; \
+          fi; \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
+            $(call functionTestcodeB); \
+            rc=$$?; \
+          fi; \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
+            $(call functionTestcodeC); \
+            rc=$$?; \
+          fi; \
+
+testcodex: \
+  $(TEST_BAR_DEBUG) \
+  $(TEST_CONFIG) \
+  $(TEST_KEYS) \
+  $(TEST_FILES)
+	TESTCODE=$(shell $(CAT) testcode.name) \
+          $(TESTCODE_COMMAND1)
+	$(TESTCODE_COMMAND1) >/dev/null
+	TESTCODE=$(shell $(CAT) testcode.name) \
+          $(TESTCODE_COMMAND2) >/dev/null; \
+	$(TESTCODE_COMMAND1) >/dev/null
+	TESTCODE=$(shell $(CAT) testcode.name) \
+          $(TESTCODE_COMMAND3) >/dev/null; \
+	$(TESTCODE_COMMAND1) >/dev/null
+	TESTCODE=$(shell $(CAT) testcode.name) \
+          $(TESTCODE_COMMAND4) >/dev/null; \
+
+testcode_list:
+	$(ECHO_NO_LF) >testcode.list
+	$(foreach z,$(TESTCODE_COMMANDS),TESTCODE_LIST=testcode.list $($z) >/dev/null;)
+
+testcode_diff:
+	$(CAT) testcode.list | $(CUT) -d " " -f 1 | $(SORT) >testcode.list.sorted
+	$(CAT) testcode.done | $(CUT) -d " " -f 1 | $(SORT) >testcode.done.sorted
+	$(DIFF) testcode.list.sorted testcode.done.sorted | $(GREP) '<' | $(SED) 's/<\s*/  /g'
+	$(RMF) testcode.list.sorted testcode.done.sorted
+
+# ----------------------------------------------------------------------------
+
 show_debug_test_code test_code:
 	@$(FIND) . -maxdepth 1 -type f -a \( -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) -print | \
           ( \
