improved testcode

diff --git a/bar/bar/Makefile.in b/bar/bar/Makefile.in
--- a/bar/bar/Makefile.in
+++ b/bar/bar/Makefile.in
@@ -2628,14 +2628,23 @@ TESTCODE_COMMAND1=$(TEST_BAR) \
                     --crypt-private-key=$(PWD)/test/key.private \
                     --archive-part-size=100K \
                     --overwrite-archive-files \
-                    -c test/test.bar test/data
+                    -c test/test-\#\#\#.bar test/data
 TESTCODE_COMMAND2=$(TEST_BAR) \
-                    -l test/test.bar
+                    --crypt-password=$(TEST_PASSWORD) \
+                    --crypt-public-key=$(PWD)/test/key.public \
+                    --crypt-private-key=$(PWD)/test/key.private \
+                    -l test/test-*.bar
 TESTCODE_COMMAND3=$(TEST_BAR) \
-                    -d test/test.bar
+                    --crypt-password=$(TEST_PASSWORD) \
+                    --crypt-public-key=$(PWD)/test/key.public \
+                    --crypt-private-key=$(PWD)/test/key.private \
+                    -d test/test-*.bar
 TESTCODE_COMMAND4=$(TEST_BAR) \
+                    --crypt-password=$(TEST_PASSWORD) \
+                    --crypt-public-key=$(PWD)/test/key.public \
+                    --crypt-private-key=$(PWD)/test/key.private \
                     --destination=test/restore \
-                    -x test/test.bar
+                    -x test/test-*.bar
 
 .PHONY: testcode_init testcode testcodex testcode_list 
 
@@ -2646,52 +2655,58 @@ testcode_init:
 
 testcode: $(TEST_BAR) $(TEST_KEYS) $(TEST_FILES)
 	rc=$(TESTCODE_EXITCODE); \
-        until test $$rc -ne $(TESTCODE_EXITCODE); do \
-          if test $$rc -eq $(TESTCODE_EXITCODE); then \
+        while test $$rc -eq $(TESTCODE_EXITCODE); do \
+          rc=0; \
+          rc1=0; \
+          rc2=0; \
+          rc3=0; \
+          rc4=0; \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
             TESTCODE_LIST=testcode.list TESTCODE_NAME=testcode.name TESTCODE_DONE=testcode.done \
-              $(TESTCODE_COMMAND1); \
-            rc=$$?; \
-            if test $$rc -ne $(TESTCODE_EXITCODE); then \
-              $(ECHO) "Fail: TESTCODE=$(shell $(CAT) testcode.name) $(TESTCODE_COMMAND1)"; \
-            fi; \
+              $(TESTCODE_COMMAND1) > /dev/null; \
+            rc1=$$?; \
+            rc=$$rc1; \
           fi;\
           \
-          if test $$rc -eq $(TESTCODE_EXITCODE); then \
-            $(TESTCODE_COMMAND1); \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
+            $(TESTCODE_COMMAND1) > /dev/null; \
             TESTCODE_LIST=testcode.list TESTCODE_NAME=testcode.name TESTCODE_DONE=testcode.done \
-              $(TESTCODE_COMMAND2); \
-            rc=$$?; \
-            if test $$rc -ne $(TESTCODE_EXITCODE); then \
-              $(ECHO) "Fail: TESTCODE=$(shell $(CAT) testcode.name) $(TESTCODE_COMMAND2)"; \
-            fi; \
+              $(TESTCODE_COMMAND2) > /dev/null; \
+            rc2=$$?; \
+            rc=$$rc2; \
           fi;\
           \
-          if test $$rc -eq $(TESTCODE_EXITCODE); then \
-            $(TESTCODE_COMMAND1); \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
+            $(TESTCODE_COMMAND1) > /dev/null; \
             TESTCODE_LIST=testcode.list TESTCODE_NAME=testcode.name TESTCODE_DONE=testcode.done \
-              $(TESTCODE_COMMAND3); \
-            rc=$$?; \
-            if test $$rc -ne $(TESTCODE_EXITCODE); then \
-              $(TESTCODE_COMMAND1); \
-              $(ECHO) "Fail: TESTCODE=$(shell $(CAT) testcode.name) $(TESTCODE_COMMAND3)"; \
-            fi; \
+              $(TESTCODE_COMMAND3) > /dev/null; \
+            rc3=$$?; \
+            rc=$$rc3; \
           fi;\
           \
-          if test $$rc -eq $(TESTCODE_EXITCODE); then \
-            $(TESTCODE_COMMAND1); \
+          if test $$rc -ne $(TESTCODE_EXITCODE); then \
+            $(TESTCODE_COMMAND1) > /dev/null; \
             TESTCODE_LIST=testcode.list TESTCODE_NAME=testcode.name TESTCODE_DONE=testcode.done \
-              $(TESTCODE_COMMAND4); \
-            rc=$$?; \
-            if test $$rc -ne $(TESTCODE_EXITCODE); then \
-              $(ECHO) "Fail: TESTCODE=$(shell $(CAT) testcode.name) $(TESTCODE_COMMAND4)"; \
-            fi; \
+              $(TESTCODE_COMMAND4) > /dev/null; \
+            rc4=$$?; \
+            rc=$$rc4; \
           fi;\
           \
           if test $$rc -eq $(TESTCODE_EXITCODE); then \
             $(CAT) testcode.name >> testcode.done; \
           else \
-echo rc=$$rc; \
-            exit 1; \
+            if test $$rc1 -ne $(TESTCODE_EXITCODE); then \
+              $(ECHO) "Fail: TESTCODE=$(shell $(CAT) testcode.name) $(TESTCODE_COMMAND1)"; \
+            fi; \
+            if test $$rc2 -ne $(TESTCODE_EXITCODE); then \
+              $(ECHO) "Fail: TESTCODE=$(shell $(CAT) testcode.name) $(TESTCODE_COMMAND2)"; \
+            fi; \
+            if test $$rc3 -ne $(TESTCODE_EXITCODE); then \
+              $(ECHO) "Fail: TESTCODE=$(shell $(CAT) testcode.name) $(TESTCODE_COMMAND3)"; \
+            fi; \
+            if test $$rc4 -ne $(TESTCODE_EXITCODE); then \
+              $(ECHO) "Fail: TESTCODE=$(shell $(CAT) testcode.name) $(TESTCODE_COMMAND4)"; \
+            fi; \
           fi; \
         done
 
