check if java is installed

diff --git a/bar/barcontrol/barcontrol.in b/bar/barcontrol/barcontrol.in
--- a/bar/barcontrol/barcontrol.in
+++ b/bar/barcontrol/barcontrol.in
@@ -28,8 +28,20 @@ case `uname` in
     ;;
 esac
 
-# java, java flags, JAR
+# check for java
 JAVA="java"
+type $JAVA 1>/dev/null 2>/dev/null
+if test $? -ne 0; then
+  echo >&2 "ERROR: cannot not run $JAVA command"
+  exit 1
+fi
+$JAVA -version 1>/dev/null 2>/dev/null
+if test $? -ne 0; then
+  echo >&2 "ERROR: cannot not run $JAVA command - VM failure?"
+  exit 1
+fi
+
+# java flags, JAR
 case $HOST_PLATFORM in
   linux)
     JAVA_FLAGS="@JAVA_FLAGS@"
@@ -67,7 +79,7 @@ case $HOST_PLATFORM in
 esac
 
 # check X11 server connection
-xset -q > /dev/null
+xset -q 1>/dev/null
 rc=$?
 if test $rc -ne 0; then
   echo >&2 "ERROR: cannot connect to X11 server. Please check DISPLAY variable and rights to connect to X11 server."
