improved X11 test

diff --git a/bar/barcontrol/barcontrol.in b/bar/barcontrol/barcontrol.in
--- a/bar/barcontrol/barcontrol.in
+++ b/bar/barcontrol/barcontrol.in
@@ -79,11 +79,15 @@ case $HOST_PLATFORM in
 esac
 
 # check X11 server connection
-xset -q 1>/dev/null
+xset -h 1>/dev/null 2>/dev/null
 rc=$?
-if test $rc -ne 0; then
-  echo >&2 "ERROR: cannot connect to X11 server. Please check DISPLAY variable and rights to connect to X11 server."
-  exit 1
+if test $rc -eq 0; then
+  xset -q 1>/dev/null 2>/dev/null
+  rc=$?
+  if test $rc -ne 0; then
+    echo >&2 "ERROR: cannot connect to X11 server. Please check DISPLAY variable and rights to connect to X11 server."
+    exit 1
+  fi
 fi
 
 # run main
