: service: do not fork

diff --git a/bar/scripts/barserver-debian b/bar/scripts/barserver-debian
--- a/bar/scripts/barserver-debian
+++ b/bar/scripts/barserver-debian
@@ -21,16 +21,13 @@
 # Author: Matthias Albert <matthias@linux4experts.de>
 
 PATH=/usr/sbin:/usr/bin:/sbin:/bin
-DESC="barserver"
 NAME=bar
-DAEMON=/usr/bin/$NAME
-CONFIGFILE=/etc/bar/bar.cfg
-DAEMON_ARGS="-f $CONFIGFILE --daemon"
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/barserver
-
-# Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+BAR_BIN=/usr/bin/$NAME
+BAR_CONFIG_FILENAME=/etc/bar/bar.cfg
+BAR_PID_FILENAME=/var/run/$NAME.pid
+BAR_ARGS="--config $BAR_CONFIG_FILENAME --daemon --pid-file=$BAR_PID_FILENAME --verbose=0 --quiet"
+BAR_SCRIPT_FILENAME=/etc/init.d/barserver
+DESCRIPTION="barserver"
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
@@ -42,6 +39,17 @@ SCRIPTNAME=/etc/init.d/barserver
 # Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
+# check for binaries
+if test ! -x $BAR_BIN; then
+  echo "$BAR_BIN not installed"
+  exit 5
+fi
+
+# check for configuration file
+if test ! -r $BAR_CONFIG_FILENAME; then
+  echo "$BAR_CONFIG_FILENAME cannot be read"
+  exit 6
+fi
 
 #
 # Function that starts the daemon/service
@@ -52,10 +60,10 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+	start-stop-daemon --start --quiet --pidfile $BAR_PID_FILENAME --exec $BAR_BIN --test > /dev/null \
 		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
+	start-stop-daemon --start --quiet --pidfile $BAR_PID_FILENAME --exec $BAR_BIN -- \
+		$BAR_ARGS \
 		|| return 2
 }
 
@@ -69,7 +77,7 @@ do_stop()
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $BAR_PID_FILENAME --name $NAME
 	RETVAL="$?"
 	[ "$RETVAL" = 2 ] && return 2
 	# Wait for children to finish too if this is a daemon that forks
@@ -78,10 +86,10 @@ do_stop()
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $BAR_BIN
 	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
+	rm -f $BAR_PID_FILENAME
 	return "$RETVAL"
 }
 
@@ -94,13 +102,13 @@ do_reload() {
 	# restarting (for example, when it is sent a SIGHUP),
 	# then implement that here.
 	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $BAR_PID_FILENAME --name $NAME
 	return 0
 }
 
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESCRIPTION" "$NAME"
 	do_start
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
@@ -108,7 +116,7 @@ case "$1" in
 	esac
 	;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESCRIPTION" "$NAME"
 	do_stop
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
@@ -120,7 +128,7 @@ case "$1" in
 	# If do_reload() is not implemented then leave this commented out
 	# and leave 'force-reload' as an alias for 'restart'.
 	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#log_daemon_msg "Reloading $DESCRIPTION" "$NAME"
 	#do_reload
 	#log_end_msg $?
 	#;;
@@ -129,7 +137,7 @@ case "$1" in
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
+	log_daemon_msg "Restarting $DESCRIPTION" "$NAME"
 	do_stop
 	case "$?" in
 	  0|1)
@@ -147,8 +155,8 @@ case "$1" in
 	esac
 	;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+	#echo "Usage: $BAR_SCRIPT_FILENAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $BAR_SCRIPT_FILENAME {start|stop|restart|force-reload}" >&2
 	exit 3
 	;;
 esac
