added some default values

diff --git a/bar/configure b/bar/configure
--- a/bar/configure
+++ b/bar/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=
 
 ac_unique_file="."
 ac_unique_file="bar.c"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC LD STRIP CC_FLAGS CC_WARN_FLAGS CC_OPTIMIZE CC_DEFINES CC_INCLUDES LD_FLAGS LIBRARY_PATHS LIBRARIES STATIC_LIBRARIES INSTALL_DIR PERL CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_DIR INSTALL_BIN_DIR CONFIG_DIR TLS_DIR CC LD STRIP CC_FLAGS CC_WARN_FLAGS CC_OPTIMIZE CC_DEFINES CC_INCLUDES LD_FLAGS LIBRARY_PATHS LIBRARIES STATIC_LIBRARIES PERL INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -811,6 +811,14 @@ Optional Features:
   --disable-gcrypt        disable gcrypt support
   --disable-tls           disable TLS support
   --disable-largefile     omit support for large files
+
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-config-dir=<path>
+                          configuration directory (default: /etc)
+  --with-tls-dir=<path>   TLS/SLL configuration and certificate directory
+                          (default: /etc/ssl)
 
 Some influential environment variables:
   CC          C compiler command
@@ -1362,6 +1370,7 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 
 
+
 CC_FLAGS=""
 CC_DEFINES=""
 CC_OPTIMIZE=""
@@ -1380,10 +1389,26 @@ ENABLE_GCRYPT="yes"
 ENABLE_TLS="yes"
 
 
-INSTALL="$INSTALL -c"
 
 
 
+# Check whether --with-config-dir or --without-config-dir was given.
+if test "${with_config_dir+set}" = set; then
+  withval="$with_config_dir"
+  CONFIG_DIR=$withval
+else
+  CONFIG_DIR=/etc
+
+fi;
+
+# Check whether --with-tls-dir or --without-tls-dir was given.
+if test "${with_tls_dir+set}" = set; then
+  withval="$with_tls_dir"
+  TLS_DIR=$withval
+else
+  TLS_DIR=/etc/ssl
+
+fi;
 
 
 # Check whether --enable-debug or --disable-debug was given.
@@ -1601,6 +1626,95 @@ fi
   test -n "$PERL" && break
 done
 
+if test -z "$PERL"; then
+  { { echo "$as_me:$LINENO: error: Cannot find a 'perl' in PATH. Please check your PATH environment variable." >&5
+echo "$as_me: error: Cannot find a 'perl' in PATH. Please check your PATH environment variable." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+# Find a good install program.  We prefer a C program (faster),
+# so one script is as good as another.  But avoid the broken or
+# incompatible versions:
+# SysV /etc/install, /usr/sbin/install
+# SunOS /usr/etc/install
+# IRIX /sbin/install
+# AIX /bin/install
+# AmigaOS /C/install, which installs bootblocks on floppy discs
+# AIX 4 /usr/bin/installbsd, which doesn't work without a -g flag
+# AFS /usr/afsws/bin/install, which mishandles nonexistent args
+# SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
+# OS/2's system install, which has a completely different semantic
+# ./install, which can be erroneously created by make from ./install.sh.
+echo "$as_me:$LINENO: checking for a BSD-compatible install" >&5
+echo $ECHO_N "checking for a BSD-compatible install... $ECHO_C" >&6
+if test -z "$INSTALL"; then
+if test "${ac_cv_path_install+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  # Account for people who put trailing slashes in PATH elements.
+case $as_dir/ in
+  ./ | .// | /cC/* | \
+  /etc/* | /usr/sbin/* | /usr/etc/* | /sbin/* | /usr/afsws/bin/* | \
+  ?:\\/os2\\/install\\/* | ?:\\/OS2\\/INSTALL\\/* | \
+  /usr/ucb/* ) ;;
+  *)
+    # OSF1 and SCO ODT 3.0 have their own names for install.
+    # Don't use installbsd from OSF since it installs stuff as root
+    # by default.
+    for ac_prog in ginstall scoinst install; do
+      for ac_exec_ext in '' $ac_executable_extensions; do
+	if $as_executable_p "$as_dir/$ac_prog$ac_exec_ext"; then
+	  if test $ac_prog = install &&
+	    grep dspmsg "$as_dir/$ac_prog$ac_exec_ext" >/dev/null 2>&1; then
+	    # AIX install.  It has an incompatible calling convention.
+	    :
+	  elif test $ac_prog = install &&
+	    grep pwplus "$as_dir/$ac_prog$ac_exec_ext" >/dev/null 2>&1; then
+	    # program-specific install script used by HP pwplus--don't use.
+	    :
+	  else
+	    ac_cv_path_install="$as_dir/$ac_prog$ac_exec_ext -c"
+	    break 3
+	  fi
+	fi
+      done
+    done
+    ;;
+esac
+done
+
+
+fi
+  if test "${ac_cv_path_install+set}" = set; then
+    INSTALL=$ac_cv_path_install
+  else
+    # As a last resort, use the slow shell script.  We don't cache a
+    # path for INSTALL within a source directory, because that will
+    # break other packages using the cache if that directory is
+    # removed, or if the path is relative.
+    INSTALL=$ac_install_sh
+  fi
+fi
+echo "$as_me:$LINENO: result: $INSTALL" >&5
+echo "${ECHO_T}$INSTALL" >&6
+
+# Use test -z because SunOS4 sh mishandles braces in ${var-val}.
+# It thinks the first close brace ends the variable substitution.
+test -z "$INSTALL_PROGRAM" && INSTALL_PROGRAM='${INSTALL}'
+
+test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
+
+test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
+
+if test -z "$INSTALL"; then
+  { { echo "$as_me:$LINENO: error: Cannot find a 'install' in PATH. Please check your PATH environment variable." >&5
+echo "$as_me: error: Cannot find a 'install' in PATH. Please check your PATH environment variable." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 CC_DEFINES="$CC_DEFINES"
 if test "$ENABLE_DEBUG" = "yes"; then
@@ -5096,6 +5210,17 @@ fi
 
 
 
+cat >>confdefs.h <<_ACEOF
+#define CONFIG_DIR "$CONFIG_DIR"
+_ACEOF
+
+
+cat >>confdefs.h <<_ACEOF
+#define TLS_DIR "$TLS_DIR"
+_ACEOF
+
+
+
           ac_config_headers="$ac_config_headers config.h"
 
 
@@ -5109,6 +5234,20 @@ fi
 
 
 
+
+if test "$prefix" = "NONE"; then
+  prefix=/usr/local
+fi
+INSTALL_DIR=$prefix
+if test "$bindir" = "\${exec_prefix}/bin"; then
+  if test "$exec_prefix" = NONE; then
+    INSTALL_BIN_DIR=$prefix/bin
+  else
+    INSTALL_BIN_DIR=$exec_prefix
+  fi
+else
+  INSTALL_BIN_DIR=$bindir
+fi
 
           ac_config_files="$ac_config_files Makefile"
 
@@ -5549,6 +5688,7 @@ Copyright (C) 2003 Free Software Foundation, Inc.
 This config.status script is free software; the Free Software Foundation
 gives unlimited permission to copy, distribute and modify it."
 srcdir=$srcdir
+INSTALL="$INSTALL"
 _ACEOF
 
 cat >>$CONFIG_STATUS <<\_ACEOF
@@ -5752,6 +5892,10 @@ s,@host@,$host,;t t
 s,@host_cpu@,$host_cpu,;t t
 s,@host_vendor@,$host_vendor,;t t
 s,@host_os@,$host_os,;t t
+s,@INSTALL_DIR@,$INSTALL_DIR,;t t
+s,@INSTALL_BIN_DIR@,$INSTALL_BIN_DIR,;t t
+s,@CONFIG_DIR@,$CONFIG_DIR,;t t
+s,@TLS_DIR@,$TLS_DIR,;t t
 s,@CC@,$CC,;t t
 s,@LD@,$LD,;t t
 s,@STRIP@,$STRIP,;t t
@@ -5764,8 +5908,10 @@ s,@LD_FLAGS@,$LD_FLAGS,;t t
 s,@LIBRARY_PATHS@,$LIBRARY_PATHS,;t t
 s,@LIBRARIES@,$LIBRARIES,;t t
 s,@STATIC_LIBRARIES@,$STATIC_LIBRARIES,;t t
-s,@INSTALL_DIR@,$INSTALL_DIR,;t t
 s,@PERL@,$PERL,;t t
+s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
+s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
+s,@INSTALL_DATA@,$INSTALL_DATA,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
 s,@CPPFLAGS@,$CPPFLAGS,;t t
@@ -5935,6 +6081,10 @@ case $ac_abs_builddir in
 esac
 
 
+  case $INSTALL in
+  [\\/$]* | ?:[\\/]* ) ac_INSTALL=$INSTALL ;;
+  *) ac_INSTALL=$ac_top_builddir$INSTALL ;;
+  esac
 
   if test x"$ac_file" != x-; then
     { echo "$as_me:$LINENO: creating $ac_file" >&5
@@ -5996,6 +6146,7 @@ s,@builddir@,$ac_builddir,;t t
 s,@abs_builddir@,$ac_abs_builddir,;t t
 s,@top_builddir@,$ac_top_builddir,;t t
 s,@abs_top_builddir@,$ac_abs_top_builddir,;t t
+s,@INSTALL@,$ac_INSTALL,;t t
 " $ac_file_inputs | (eval "$ac_sed_cmds") >$tmp/out
   rm -f $tmp/stdin
   if test x"$ac_file" != x-; then
