added support to temporary compile third party packages when located in the build sub-directory

diff --git a/bar/configure.in b/bar/configure.in
--- a/bar/configure.in
+++ b/bar/configure.in
@@ -1,13 +1,20 @@
 dnl --------------------------------------------------------------------
 dnl
 dnl $Source: /home/torsten/cvs/bar/configure.in,v $
-dnl $Revision: 1.27 $
+dnl $Revision: 1.28 $
 dnl $Author: torsten $
 dnl Contents: BAR auto-configure script
 dnl
 dnl --------------------------------------------------------------------
 
 dnl ----------------------- additional macros --------------------------
+
+
+dnl --- print compile info
+AC_DEFUN([AC_MSG_COMPILE],
+[
+  _AS_ECHO_N([Compile $1... ])
+])
 
 dnl --- check if C compiler long long data type available
 # (original macro from http://ac-archive.sourceforge.net/C_Support/ac_c_long_long.html)
@@ -142,6 +149,12 @@ AC_SUBST(PLATFORM)                          dnl platform
 
 AC_SUBST(ENABLE_DEBUG)                      dnl "yes" for debug version, "no" otherwise
 AC_SUBST(ENABLE_GUI)                        dnl "yes" to build GUI, "no" otherwise
+AC_SUBST(ENABLE_BZIP2)                      dnl "yes" for bzip2 support, "no" otherwise
+AC_SUBST(ENABLE_LZMA)                       dnl "yes" for lzma support, "no" otherwise
+AC_SUBST(ENABLE_GCRYPT)                     dnl "yes" for gcrypt support, "no" otherwise
+AC_SUBST(ENABLE_FTP)                        dnl "yes" for ftp support, "no" otherwise
+AC_SUBST(ENABLE_SSH)                        dnl "yes" for ssh support, "no" otherwise
+AC_SUBST(ENABLE_TLS)                        dnl "yes" for tls support, "no" otherwise
 
 AC_SUBST(INSTALL_DIR)                       dnl installation directory
 AC_SUBST(INSTALL_BIN_DIR)                   dnl installation directory for binaries
@@ -199,6 +212,7 @@ STATIC_LIBRARIES=""
 ENABLE_DEBUG="no"
 ENABLE_LINK_DYNAMIC="no"
 ENABLE_BZIP2="yes"
+ENABLE_LZMA="yes"
 ENABLE_GCRYPT="yes"
 ENABLE_FTP="yes"
 ENABLE_SSH="yes"
@@ -273,6 +287,11 @@ AC_ARG_ENABLE(
   bzip2,
   AC_HELP_STRING([--disable-bzip2],[disable bzip2 support]),
   [ENABLE_BZIP2=$enableval]
+)
+AC_ARG_ENABLE(
+  lzma,
+  AC_HELP_STRING([--disable-lzma],[disable lzma support]),
+  [ENABLE_LZMA=$enableval]
 )
 AC_ARG_ENABLE(
   gcrypt,
@@ -402,58 +421,197 @@ AC_CHECK_SIZEOF(void *)
 
 AC_SEARCH_LIBS(round,m,,AC_ERROR([m library not found]))
 AC_SEARCH_LIBS(pthread_create,pthread,,AC_ERROR([pthread library not found]))
+
 if test $ENABLE_LINK_DYNAMIC = "yes"; then
   AC_SEARCH_LIBS(zlibVersion,z,[HAVE_Z=1;LIBRARIES="$LIBRARIES z";AC_DEFINE(HAVE_Z,1,[z installed])])
 else
   AC_SEARCH_LIBS(zlibVersion,z,[HAVE_Z=1;STATIC_LIBRARIES="$STATIC_LIBRARIES z";AC_DEFINE(HAVE_Z,1,[z installed])])
 fi
+
 if test $ENABLE_BZIP2 = "yes"; then
-  if test $ENABLE_LINK_DYNAMIC = "yes"; then
-    AC_SEARCH_LIBS(BZ2_bzCompressInit,bz2,[HAVE_BZ2=1;LIBRARIES="$LIBRARIES bz2";AC_DEFINE(HAVE_BZ2,1,[bzip2 installed])])
+  if test -d bzip2 -o -d "`readlink bzip2`"; then
+    dnl compile bzip2 library
+    AC_MSG_COMPILE([bzip2])
+    cwd=`pwd`
+    (cd bzip2; make && make install PREFIX=$cwd/tmp) 1>/dev/null 2>/dev/null
+    if test $? -eq 0; then
+      HAVE_BZ2=1
+      CC_INCLUDES="$CC_INCLUDES $cwd/tmp/include"
+      LIBRARY_PATHS="$LIBRARY_PATHS $cwd/tmp/lib"
+      STATIC_LIBRARIES="$STATIC_LIBRARIES bz2"
+      AC_DEFINE(HAVE_BZ2,1,[bzip2 installed (local)])
+
+      AC_MSG_RESULT([done])
+    else
+      AC_MSG_RESULT([fail])
+    fi
   else
-    AC_SEARCH_LIBS(BZ2_bzCompressInit,bz2,[HAVE_BZ2=1;STATIC_LIBRARIES="$STATIC_LIBRARIES bz2";AC_DEFINE(HAVE_BZ2,1,[bzip2 installed])])
+    dnl search for installed bzip2 library
+    if test $ENABLE_LINK_DYNAMIC = "yes"; then
+      AC_SEARCH_LIBS(BZ2_bzCompressInit,bz2,[HAVE_BZ2=1;LIBRARIES="$LIBRARIES bz2";AC_DEFINE(HAVE_BZ2,1,[bzip2 installed])])
+    else
+      AC_SEARCH_LIBS(BZ2_bzCompressInit,bz2,[HAVE_BZ2=1;STATIC_LIBRARIES="$STATIC_LIBRARIES bz2";AC_DEFINE(HAVE_BZ2,1,[bzip2 installed])])
+    fi
   fi
 fi
+
+if test $ENABLE_LZMA = "yes"; then
+  if test -d xz -o -d "`readlink xz`"; then
+    dnl compile lzma library
+    AC_MSG_COMPILE([xz utils])
+    cwd=`pwd`
+    (cd xz; ./configure --prefix=$cwd/tmp && make && make install) 1>/dev/null 2>/dev/null
+    if test $? -eq 0; then
+      HAVE_LZMA=1
+      CC_INCLUDES="$CC_INCLUDES $cwd/tmp/include"
+      LIBRARY_PATHS="$LIBRARY_PATHS $cwd/tmp/lib"
+      STATIC_LIBRARIES="$STATIC_LIBRARIES lzma"
+      AC_DEFINE(HAVE_LZMA,1,[lzma installed (local)])
+
+      AC_MSG_RESULT([done])
+    else
+      AC_MSG_RESULT([fail])
+    fi
+  else
+    dnl search for installed lzma library
+    if test $ENABLE_LINK_DYNAMIC = "yes"; then
+      AC_SEARCH_LIBS(lzma_easy_encoder,lzma,[HAVE_LZMA=1;LIBRARIES="$LIBRARIES lzma";AC_DEFINE(HAVE_LZMA,1,[lzma installed])])
+    else
+      AC_SEARCH_LIBS(lzma_easy_encoder,lzma,[HAVE_LZMA=1;STATIC_LIBRARIES="$STATIC_LIBRARIES lzma";AC_DEFINE(HAVE_LZMA,1,[lzma installed])])
+    fi
+  fi
+fi
+
 if test $ENABLE_GCRYPT = "yes"; then
-  AC_CHECK_TYPE(gcry_cipher_hd_t,,AC_MSG_WARN([no or wrong version of gcrypt. gcrypt version >=1.2.4 needed. Disabled gcrypt support.]); ENABLE_GCRYPT=no,[#include <gcrypt.h>])
-fi
-if test $ENABLE_GCRYPT = "yes"; then
-  if test $ENABLE_LINK_DYNAMIC = "yes"; then
-    AC_SEARCH_LIBS(gcry_check_version,gcrypt,[HAVE_GCRYPT=1;LIBRARIES="$LIBRARIES gcrypt";AC_DEFINE(HAVE_GCRYPT,1,[gcrypt installed])])
+  if test \( -d libgpg -o -d "`readlink libgpg`" \) -a \( -d libgcrypt -o -d "`readlink libgcrypt`" \); then
+    dnl compile libgcrypt library
+    AC_MSG_COMPILE([gpg-error])
+    cwd=`pwd`
+    (cd libgpg; ./configure --prefix=$cwd/tmp && make && make install) 1>/dev/null 2>/dev/null
+    if test $? -eq 0; then
+      AC_MSG_RESULT([done])
+
+      AC_MSG_COMPILE([gcrypt])
+      (cd libgcrypt; ./configure --prefix=$cwd/tmp --with-gpg-error-prefix=$cwd/tmp && make && make install) 1>/dev/null 2>/dev/null
+      if test $? -eq 0; then
+        HAVE_GCRYPT=1
+        HAVE_GPG_ERROR=1
+        CC_INCLUDES="$CC_INCLUDES $cwd/tmp/include"
+        LIBRARY_PATHS="$LIBRARY_PATHS $cwd/tmp/lib"
+        STATIC_LIBRARIES="$STATIC_LIBRARIES gpg-error gcrypt"
+        AC_DEFINE(HAVE_GCRYPT,1,[gcrypt installed (local)])
+
+        AC_MSG_RESULT([done])
+      else
+        AC_MSG_RESULT([fail])
+      fi
+    else
+      AC_MSG_RESULT([fail])
+    fi
   else
-    AC_SEARCH_LIBS(gcry_check_version,gcrypt,[HAVE_GCRYPT=1;STATIC_LIBRARIES="$STATIC_LIBRARIES gcrypt";AC_DEFINE(HAVE_GCRYPT,1,[gcrypt installed])])
-  fi
-  LIBRARIES="$LIBRARIES dl"
-  if test $ENABLE_LINK_DYNAMIC = "yes"; then
-    AC_SEARCH_LIBS(gpg_strerror,gpg-error,[HAVE_GPG_ERROR=1;LIBRARIES="$LIBRARIES gpg-error";AC_DEFINE(HAVE_GPG_ERROR,1,[GPG error installed])])
-  else
-    AC_SEARCH_LIBS(gpg_strerror,gpg-error,[HAVE_GPG_ERROR=1;STATIC_LIBRARIES="$STATIC_LIBRARIES gpg-error";AC_DEFINE(HAVE_GPG_ERROR,1,[GPG error installed])])
+    dnl search for installed gpg-error/gcrypt library
+    AC_CHECK_TYPE(gcry_cipher_hd_t,,AC_MSG_WARN([no or wrong version of gcrypt. gcrypt version >=1.2.4 needed. Disabled gcrypt support.]); ENABLE_GCRYPT=no,[#include <gcrypt.h>])
+    LIBRARIES="$LIBRARIES dl"
+    if test $ENABLE_LINK_DYNAMIC = "yes"; then
+      AC_SEARCH_LIBS(gpg_strerror,gpg-error,[HAVE_GPG_ERROR=1;LIBRARIES="$LIBRARIES gpg-error";AC_DEFINE(HAVE_GPG_ERROR,1,[GPG error installed])])
+    else
+      AC_SEARCH_LIBS(gpg_strerror,gpg-error,[HAVE_GPG_ERROR=1;STATIC_LIBRARIES="$STATIC_LIBRARIES gpg-error";AC_DEFINE(HAVE_GPG_ERROR,1,[GPG error installed])])
+    fi
+    if test $ENABLE_LINK_DYNAMIC = "yes"; then
+      AC_SEARCH_LIBS(gcry_check_version,gcrypt,[HAVE_GCRYPT=1;LIBRARIES="$LIBRARIES gcrypt";AC_DEFINE(HAVE_GCRYPT,1,[gcrypt installed])])
+    else
+      AC_SEARCH_LIBS(gcry_check_version,gcrypt,[HAVE_GCRYPT=1;STATIC_LIBRARIES="$STATIC_LIBRARIES gcrypt";AC_DEFINE(HAVE_GCRYPT,1,[gcrypt installed])])
+    fi
   fi
 fi
+
 if test $ENABLE_FTP = "yes"; then
-  if test $ENABLE_LINK_DYNAMIC = "yes"; then
-    AC_SEARCH_LIBS(FtpInit,ftp,[HAVE_FTP=1;LIBRARIES="$LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[FTP installed])])
+  if test -d ftplib -o -d "`readlink ftplib`"; then
+    dnl compile lzma library
+    AC_MSG_COMPILE([ftplib])
+    cwd=`pwd`
+    (
+     cd ftplib
+     patch -N -p1 <$cwd/ftplib-3.1-without-perror.patch 1>/dev/null 2>/dev/null
+     cd linux
+     make && cp ftplib.h $cwd/tmp/include && cp libftp.a $cwd/tmp/lib
+    ) 1>/dev/null 2>/dev/null
+    if test $? -eq 0; then
+      HAVE_FTP=1
+      CC_INCLUDES="$CC_INCLUDES $cwd/tmp/include"
+      LIBRARY_PATHS="$LIBRARY_PATHS $cwd/tmp/lib"
+      STATIC_LIBRARIES="$STATIC_LIBRARIES ftp"
+      AC_DEFINE(HAVE_FTP,1,[ftplib installed (local)])
+
+      AC_MSG_RESULT([done])
+    else
+      AC_MSG_RESULT([fail])
+    fi
   else
-    AC_SEARCH_LIBS(FtpInit,ftp,[HAVE_FTP=1;STATIC_LIBRARIES="$STATIC_LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[FTP installed])])
+    if test $ENABLE_LINK_DYNAMIC = "yes"; then
+      AC_SEARCH_LIBS(FtpInit,ftp,[HAVE_FTP=1;LIBRARIES="$LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[FTP installed])])
+    else
+      AC_SEARCH_LIBS(FtpInit,ftp,[HAVE_FTP=1;STATIC_LIBRARIES="$STATIC_LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[FTP installed])])
+    fi
   fi
 fi
+
 if test $ENABLE_SSH = "yes"; then
-  if test $ENABLE_LINK_DYNAMIC = "yes"; then
-    AC_SEARCH_LIBS(libssh2_session_init_ex,ssh2,[HAVE_SSH2=1;LIBRARIES="$LIBRARIES ssh2 crypto";AC_DEFINE(HAVE_SSH2,1,[SSH2 installed])])
+  if test -d libssh2 -o -d "`readlink libssh2`"; then
+    dnl compile lzma library
+    AC_MSG_COMPILE([libssh2])
+    cwd=`pwd`
+    (
+     cd libssh2
+     patch -N -p1 <$cwd/misc/libssh2-1.1-keepalive.patch 1>/dev/null 2>/dev/null
+     ./configure --prefix=$cwd/tmp && make && make install
+    ) 1>/dev/null 2>/dev/null
+    if test $? -eq 0; then
+      HAVE_SSH2=1
+      CC_INCLUDES="$CC_INCLUDES $cwd/tmp/include"
+      LIBRARY_PATHS="$LIBRARY_PATHS $cwd/tmp/lib"
+      STATIC_LIBRARIES="$STATIC_LIBRARIES ssh2 crypto"
+      AC_DEFINE(HAVE_SSH2,1,[ssh2 installed (local)])
+
+      AC_MSG_RESULT([done])
+    else
+      AC_MSG_RESULT([fail])
+    fi
   else
-    AC_SEARCH_LIBS(libssh2_session_init_ex,ssh2,[HAVE_SSH2=1;STATIC_LIBRARIES="$STATIC_LIBRARIES ssh2 crypto";AC_DEFINE(HAVE_SSH2,1,[SSH2 installed])])
+    if test $ENABLE_LINK_DYNAMIC = "yes"; then
+      AC_SEARCH_LIBS(libssh2_session_init_ex,ssh2,[HAVE_SSH2=1;LIBRARIES="$LIBRARIES ssh2 crypto";AC_DEFINE(HAVE_SSH2,1,[SSH2 installed])])
+    else
+      AC_SEARCH_LIBS(libssh2_session_init_ex,ssh2,[HAVE_SSH2=1;STATIC_LIBRARIES="$STATIC_LIBRARIES ssh2 crypto";AC_DEFINE(HAVE_SSH2,1,[SSH2 installed])])
+    fi
   fi
 fi
+
 if test $ENABLE_TLS = "yes"; then
-  AC_CHECK_TYPE(gnutls_session_t,,AC_MSG_WARN([no or wrong version of gnutls. gnutls version >=2.0.1 needed. Disabled TLS support.]); ENABLE_TLS=no,[#include <gnutls/gnutls.h>])
-fi
-if test $ENABLE_TLS = "yes"; then
-  if test $ENABLE_LINK_DYNAMIC = "yes"; then
-    AC_SEARCH_LIBS(gnutls_global_init,gnutls,[HAVE_GNU_TLS=1;LIBRARIES="$LIBRARIES gnutls";AC_DEFINE(HAVE_GNU_TLS,1,[GNU TLS installed])])
-    AC_SEARCH_LIBS(asn1_length_der,tasn1,[HAVE_TASN1=1;LIBRARIES="$LIBRARIES tasn1";AC_DEFINE(HAVE_TASN1,1,[TASN.1 installed])])
+  if test -d gnutls -o -d "`readlink gnutls`"; then
+    dnl compile gnutls library
+    AC_MSG_COMPILE([gnutls])
+    cwd=`pwd`
+    (cd gnutls; ./configure --prefix=$cwd/tmp && make && make install) 1>/dev/null 2>/dev/null
+    if test $? -eq 0; then
+      HAVE_GNU_TLS=1
+      CC_INCLUDES="$CC_INCLUDES $cwd/tmp/include"
+      LIBRARY_PATHS="$LIBRARY_PATHS $cwd/tmp/lib"
+      STATIC_LIBRARIES="$STATIC_LIBRARIES gnutls"
+      AC_DEFINE(HAVE_GNU_TLS,1,[gnutls installed (local)])
+
+      AC_MSG_RESULT([done])
+    else
+      AC_MSG_RESULT([fail])
+    fi
   else
-    AC_SEARCH_LIBS(gnutls_global_init,gnutls,[HAVE_GNU_TLS=1;STATIC_LIBRARIES="$STATIC_LIBRARIES gnutls";AC_DEFINE(HAVE_GNU_TLS,1,[GNU TLS installed])])
-    AC_SEARCH_LIBS(asn1_length_der,tasn1,[HAVE_TASN1=1;STATIC_LIBRARIES="$STATIC_LIBRARIES tasn1";AC_DEFINE(HAVE_TASN1,1,[TASN.1 installed])])
+    AC_CHECK_TYPE(gnutls_session_t,,AC_MSG_WARN([no or wrong version of gnutls. gnutls version >=2.0.1 needed. Disabled TLS support.]); ENABLE_TLS=no,[#include <gnutls/gnutls.h>])
+    if test $ENABLE_LINK_DYNAMIC = "yes"; then
+      AC_SEARCH_LIBS(gnutls_global_init,gnutls,[HAVE_GNU_TLS=1;LIBRARIES="$LIBRARIES gnutls";AC_DEFINE(HAVE_GNU_TLS,1,[GNU TLS installed])])
+      AC_SEARCH_LIBS(asn1_length_der,tasn1,[HAVE_TASN1=1;LIBRARIES="$LIBRARIES tasn1";AC_DEFINE(HAVE_TASN1,1,[TASN.1 installed])])
+    else
+      AC_SEARCH_LIBS(gnutls_global_init,gnutls,[HAVE_GNU_TLS=1;STATIC_LIBRARIES="$STATIC_LIBRARIES gnutls";AC_DEFINE(HAVE_GNU_TLS,1,[GNU TLS installed])])
+      AC_SEARCH_LIBS(asn1_length_der,tasn1,[HAVE_TASN1=1;STATIC_LIBRARIES="$STATIC_LIBRARIES tasn1";AC_DEFINE(HAVE_TASN1,1,[TASN.1 installed])])
+    fi
   fi
 fi
 
@@ -537,6 +695,7 @@ AC_CONFIG_COMMANDS(BUILD_NOTE,
                     echo "  debug version    : `if test "$ENABLE_DEBUG" = "yes"; then echo yes; else echo no; fi`";
                     echo "  dynamic linked   : `if test "$ENABLE_LINK_DYNAMIC" = "yes"; then echo yes; else echo no; fi`";
                     echo "  bzip2 compression: `if test $HAVE_BZ2; then echo yes; else echo no; fi`";
+                    echo "  lzma compression : `if test $HAVE_LZMA; then echo yes; else echo no; fi`";
                     echo "  crypto support   : `if test $HAVE_GCRYPT; then echo yes; else echo no; fi`";
                     echo "  FTP support      : `if test $HAVE_FTP; then echo yes; else echo no; fi`";
                     echo "  SCP/SFTP support : `if test $HAVE_SSH2; then echo yes; else echo no; fi`";
@@ -552,6 +711,7 @@ AC_CONFIG_COMMANDS(BUILD_NOTE,
                    ENABLE_DEBUG=$ENABLE_DEBUG
                    ENABLE_LINK_DYNAMIC=$ENABLE_LINK_DYNAMIC
                    HAVE_BZ2=$HAVE_BZ2
+                   HAVE_LZMA=$HAVE_LZMA
                    HAVE_GCRYPT=$HAVE_GCRYPT
                    HAVE_FTP=$HAVE_FTP
                    HAVE_SSH2=$HAVE_SSH2
