improved error messages when package cannot be compiled

diff --git a/bar/configure.in b/bar/configure.in
--- a/bar/configure.in
+++ b/bar/configure.in
@@ -1154,8 +1154,16 @@ CC_INCLUDES="$CC_INCLUDES $cwd/packages/include"
 LIBRARY_PATHS="$LIBRARY_PATHS $cwd/packages/lib"
 
 # set variables for compile packages
-AC_SET_TOOLCHAIN_SETTINGS($CC_FLAGS,$CXX_FLAGS,$CC_DEFINES,$CC_INCLUDES,$LD_FLAGS,$LIBRARY_PATHS,$STATIC_LIBRARIES,$LIBRARIES)
+AC_SET_TOOLCHAIN_SETTINGS($CC_FLAGS,
+                          $CXX_FLAGS,
+                          $CC_DEFINES,
+                          $CC_INCLUDES,
+                          $LD_FLAGS,
+                          $LIBRARY_PATHS,
+                          $STATIC_LIBRARIES,
+                          $LIBRARIES)
 
+# compile/use zlib
 if test -d zlib -o -d "`readlink zlib`"; then
   if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
     dnl compile zlib library
@@ -1213,8 +1221,15 @@ else
       AC_SEARCH_LIBRARIES(zlibVersion,z,[HAVE_Z=1;LIBRARIES="z $LIBRARIES";AC_DEFINE(HAVE_Z,1,[z installed])])
     fi
   fi
+
+  if test -z "$HAVE_Z"; then
+    if test ! \( -d zlib -o -d "`readlink zlib`" \); then
+      AC_MSG_WARN([zlib not compiled: zlib package missing])
+    fi
+  fi
 fi
 
+# compile/use bz2
 if test $ENABLE_BZ2 = "yes"; then
   if test -d bzip2 -o -d "`readlink bzip2`"; then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -1262,9 +1277,16 @@ if test $ENABLE_BZ2 = "yes"; then
         AC_SEARCH_LIBRARIES(BZ2_bzCompressInit,bz2,[HAVE_BZ2=1;LIBRARIES="bz2 $LIBRARIES";AC_DEFINE(HAVE_BZ2,1,[bzip2 installed])])
       fi
     fi
+
+    if test -z "$HAVE_BZ2"; then
+      if test ! \( -d bzip2 -o -d "`readlink bzip2`" \); then
+        AC_MSG_WARN([bzip2 not compiled: bzip2 package missing])
+      fi
+    fi
   fi
 fi
 
+# compile/use lzma
 if test $ENABLE_LZMA = "yes"; then
   if test -d xz -o -d "`readlink xz`"; then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -1341,9 +1363,16 @@ if test $ENABLE_LZMA = "yes"; then
         AC_SEARCH_LIBRARIES(lzma_easy_encoder,lzma,[HAVE_LZMA=1;LIBRARIES="lzma $LIBRARIES";AC_DEFINE(HAVE_LZMA,1,[lzma installed])])
       fi
     fi
+
+    if test -z "$HAVE_LZMA"; then
+      if test ! \( -d xz -o -d "`readlink xz`" \); then
+        AC_MSG_WARN([lzma not compiled: xz package missing])
+      fi
+    fi
   fi
 fi
 
+# compile/use lzo
 if test $ENABLE_LZO = "yes"; then
   if test -d lzo -o -d "`readlink lzo`"; then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -1401,9 +1430,16 @@ if test $ENABLE_LZO = "yes"; then
         AC_SEARCH_LIBRARIES(lzo1x_1_compress,lzo,[HAVE_LZO=1;LIBRARIES="lzo2 $LIBRARIES";AC_DEFINE(HAVE_LZO,1,[lzo installed])])
       fi
     fi
+
+    if test -z "$HAVE_LZO"; then
+      if test ! \( -d lzo -o -d "`readlink lzo`" \); then
+        AC_MSG_WARN([lzo not compiled: lzo package missing])
+      fi
+    fi
   fi
 fi
 
+# compile/use lz4
 if test $ENABLE_LZ4 = "yes"; then
   if test -d lz4 -o -d "`readlink lz4`"; then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -1451,9 +1487,16 @@ if test $ENABLE_LZ4 = "yes"; then
         AC_SEARCH_LIBRARIES(LZ4_compress,lz4,[HAVE_LZ4=1;LIBRARIES="lz4 $LIBRARIES";AC_DEFINE(HAVE_LZ4,1,[lz4 installed])])
       fi
     fi
+
+    if test -z "$HAVE_LZ4"; then
+      if test ! \( -d lz4 -o -d "`readlink lz4`" \); then
+        AC_MSG_WARN([lz4 not compiled: lz4 package missing])
+      fi
+    fi
   fi
 fi
 
+# use xdelta3
 if test $ENABLE_XDELTA3 = "yes"; then
   if test -d xdelta3 -o -d "`readlink xdelta3`"; then
     HAVE_XDELTA=1
@@ -1464,6 +1507,7 @@ if test $ENABLE_XDELTA3 = "yes"; then
   fi
 fi
 
+# compile/use gcrypt
 if test $ENABLE_GCRYPT = "yes"; then
   if test \( -d libgpg-error -o -d "`readlink libgpg-error`" \) -a \( -d libgcrypt -o -d "`readlink libgcrypt`" \); then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -1607,9 +1651,19 @@ if test $ENABLE_GCRYPT = "yes"; then
       ],
       [#include <gcrypt.h>]
     )
+
+    if test -z "$HAVE_GCRYPT"; then
+      if test ! \( -d libgpg-error -o -d "`readlink libgpg-error`" \); then
+        AC_MSG_WARN([libgcrypt not compiled: libgpg-error package missing])
+      fi
+      if test ! \( -d libgcrypt -o -d "`readlink libgcrypt`" \); then
+        AC_MSG_WARN([libgcrypt not compiled: libgcrypt package missing])
+      fi
+    fi
   fi
 fi
 
+# compile/use gnutls
 if test $ENABLE_TLS = "yes"; then
   if test \( -d gmp -o -d "`readlink gmp`" \) -a \( -d nettle -o -d "`readlink nettle`" \) -a \( -d gnutls -o -d "`readlink gnutls`" \); then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -1769,57 +1823,22 @@ if test $ENABLE_TLS = "yes"; then
         AC_SEARCH_LIBRARIES(asn1_length_der,tasn1,[HAVE_TASN1=1;LIBRARIES="$LIBRARIES tasn1";AC_DEFINE(HAVE_TASN1,1,[TASN.1 installed])])
       fi
     fi
-  fi
-fi
 
-if test $ENABLE_FTP = "yes"; then
-  if test -d ftplib -o -d "`readlink ftplib`"; then
-    if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
-      dnl compile ftp library
-
-      AC_MSG_COMPILE([ftplib])
-      if test $result -eq 1; then
-        (cd ftplib/linux; make clean; make -j$CPU_CORES) 1>$tmpFile 2>&1
-        if test $? -ne 0; then
-          AC_MSG_RESULT([fail (make)])
-          AC_MSG_OUTPUT_LOG($tmpFile)
-          result=0
-        fi
+    if test -z "$HAVE_GNU_TLS"; then
+      if test ! \( -d gmp -o -d "`readlink gmp`" \); then
+        AC_MSG_WARN([gnutls not compiled: gmp package missing])
       fi
-      if test $result -eq 1; then
-        (cd ftplib/linux; cp ftplib.h $cwd/packages/include && cp libftp.a $cwd/packages/lib) 1>$tmpFile 2>&1
-        if test $? -ne 0; then
-          AC_MSG_RESULT([fail (install)])
-          AC_MSG_OUTPUT_LOG($tmpFile)
-          result=0
-        fi
+      if test ! \( -d nettle -o -d "`readlink nettle`" \); then
+        AC_MSG_WARN([gnutls not compiled: nettle package missing])
       fi
-      if test $result -eq 1; then
-        AC_MSG_RESULT([done])
-      fi
-    else
-      result=1
-    fi
-
-    if test $result -eq 1; then
-      HAVE_FTP=1
-      STATIC_LIBRARIES="$STATIC_LIBRARIES ftp"
-      AC_DEFINE(HAVE_FTP,1,[ftplib installed (local)])
-    fi
-  else
-    if test $ENABLE_LINK_DYNAMIC = "yes"; then
-      AC_SEARCH_LIBRARIES(FtpInit,ftp,[HAVE_FTP=1;LIBRARIES="$LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[FTP installed])])
-    else
-      if test -z "$HAVE_FTP"; then
-        AC_SEARCH_STATIC_LIBRARIES(FtpInit,ftp,[HAVE_FTP=1;STATIC_LIBRARIES="$STATIC_LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[static FTP installed])])
-      fi
-      if test -z "$HAVE_FTP"; then
-        AC_SEARCH_LIBRARIES(FtpInit,ftp,[HAVE_FTP=1;LIBRARIES="$LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[FTP installed])])
+      if test ! \( -d gnutls -o -d "`readlink gnutls`" \); then
+        AC_MSG_WARN([gnutls not compiled: gnutls package missing])
       fi
     fi
   fi
 fi
 
+# compile/use openssl
 if test $ENABLE_SSH = "yes"; then
   if test -d openssl -o -d "`readlink openssl`"; then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -1984,6 +2003,12 @@ if test $ENABLE_SSH = "yes"; then
         AC_SEARCH_LIBRARIES(libssh2_session_init_ex,ssh2,[HAVE_SSH2=1;LIBRARIES="$LIBRARIES ssh2";AC_DEFINE(HAVE_SSH2,1,[SSH2 installed])])
       fi
     fi
+
+    if test -z "$HAVE_SSH2"; then
+      if test ! \( -d libssh2 -o -d "`readlink libssh2`" \); then
+        AC_MSG_WARN([libssh2 not compiled: libssh2 package missing])
+      fi
+    fi
   fi
 
   dnl link libcrypto, too, if available (may be needed by some libssh2 implementations)
@@ -1999,6 +2024,7 @@ if test $ENABLE_SSH = "yes"; then
   fi
 fi
 
+# compile/use curl
 if test $ENABLE_CURL = "yes"; then
   if test \( -d curl -o -d "`readlink curl`" \) -a \( -d c-ares -o -d "`readlink c-ares`" \) -a \( -d mxml -o -d "`readlink mxml`" \); then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -2251,6 +2277,22 @@ if test $ENABLE_CURL = "yes"; then
         AC_SEARCH_LIBRARIES(curl_global_init,curl,[HAVE_CURL=1;LIBRARIES="$LIBRARIES curl";AC_DEFINE(HAVE_CURL,1,[curl installed])])
       fi
     fi
+
+    if test -z "$HAVE_CURL"; then
+      if test ! \( -d curl -o -d "`readlink curl`" \); then
+        AC_MSG_WARN([curl not compiled: curl package missing])
+      fi
+    fi
+    if test -z "$HAVE_CARES"; then
+      if test ! \( -d c-ares -o -d "`readlink c-ares`" \); then
+        AC_MSG_WARN([libssh2 not compiled: c-ares package missing])
+      fi
+    fi
+    if test -z "$HAVE_MXML"; then
+      if test ! \( -d mxml -o -d "`readlink mxml`" \); then
+        AC_MSG_WARN([libssh2 not compiled: mxml package missing])
+      fi
+    fi
   fi
 
   if test "$HAVE_CURL"; then
@@ -2263,6 +2305,62 @@ if test $ENABLE_CURL = "yes"; then
   fi
 fi
 
+# compile/ ftplib (Note: not used if curl is available)
+if test $ENABLE_FTP = "yes" -a -z "$HAVE_CURL"; then
+  if test -d ftplib -o -d "`readlink ftplib`"; then
+    if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
+      dnl compile ftp library
+
+      AC_MSG_COMPILE([ftplib])
+      if test $result -eq 1; then
+        (cd ftplib/linux; make clean; make -j$CPU_CORES) 1>$tmpFile 2>&1
+        if test $? -ne 0; then
+          AC_MSG_RESULT([fail (make)])
+          AC_MSG_OUTPUT_LOG($tmpFile)
+          result=0
+        fi
+      fi
+      if test $result -eq 1; then
+        (cd ftplib/linux; cp ftplib.h $cwd/packages/include && cp libftp.a $cwd/packages/lib) 1>$tmpFile 2>&1
+        if test $? -ne 0; then
+          AC_MSG_RESULT([fail (install)])
+          AC_MSG_OUTPUT_LOG($tmpFile)
+          result=0
+        fi
+      fi
+      if test $result -eq 1; then
+        AC_MSG_RESULT([done])
+      fi
+    else
+      result=1
+    fi
+
+    if test $result -eq 1; then
+      HAVE_FTP=1
+      STATIC_LIBRARIES="$STATIC_LIBRARIES ftp"
+      AC_DEFINE(HAVE_FTP,1,[ftplib installed (local)])
+    fi
+  else
+    if test $ENABLE_LINK_DYNAMIC = "yes"; then
+      AC_SEARCH_LIBRARIES(FtpInit,ftp,[HAVE_FTP=1;LIBRARIES="$LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[FTP installed])])
+    else
+      if test -z "$HAVE_FTP"; then
+        AC_SEARCH_STATIC_LIBRARIES(FtpInit,ftp,[HAVE_FTP=1;STATIC_LIBRARIES="$STATIC_LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[static FTP installed])])
+      fi
+      if test -z "$HAVE_FTP"; then
+        AC_SEARCH_LIBRARIES(FtpInit,ftp,[HAVE_FTP=1;LIBRARIES="$LIBRARIES ftp";AC_DEFINE(HAVE_FTP,1,[FTP installed])])
+      fi
+    fi
+
+    if test -z "$HAVE_FTP"; then
+      if test ! \( -d ftplib -o -d "`readlink ftplib`" \); then
+        AC_MSG_WARN([ftplib not compiled: ftplib package missing])
+      fi
+    fi
+  fi
+fi
+
+# compile/use cdio
 if test $ENABLE_ISO9660 = "yes"; then
   if test -d libiconv -o -d "`readlink libiconv`"; then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -2379,9 +2477,16 @@ if test $ENABLE_ISO9660 = "yes"; then
         AC_SEARCH_LIBRARIES(iso9660_open,iso9660,[HAVE_ISO9660=1;LIBRARIES="$LIBRARIES iso9660 cdio";AC_DEFINE(HAVE_ISO9660,1,[iso9660 installed])])
       fi
     fi
+
+    if test -z "$HAVE_ISO9660"; then
+      if test ! \( -d libcdio -o -d "`readlink libcdio`" \); then
+        AC_MSG_WARN([libcdio not compiled: libcdio package missing])
+      fi
+    fi
   fi
 fi
 
+# compile/use pcre
 if test $ENABLE_PCRE = "yes"; then
   if test -d pcre -o -d "`readlink pcre`"; then
     if test "$ENABLE_PACKAGE_COMPILE" = "yes"; then
@@ -2469,6 +2574,12 @@ if test $ENABLE_PCRE = "yes"; then
       fi
       if test -z "$HAVE_PCRE"; then
         AC_SEARCH_LIBRARIES(pcre,pcre_compile,[HAVE_PCRE=1;LIBRARIES="$LIBRARIES pcre";AC_DEFINE(HAVE_PCRE,1,[pcre installed])])
+      fi
+    fi
+
+    if test -z "$HAVE_PCRE"; then
+      if test ! \( -d pcre -o -d "`readlink pcre`" \); then
+        AC_MSG_WARN([pcre not compiled: pcre package missing])
       fi
     fi
   fi
@@ -2587,6 +2698,12 @@ if test $ENABLE_BREAKPAD = "yes"; then
       fi
     fi
 
+    if test -z "$HAVE_BREAKPAD"; then
+      if test ! \( -d breakpad -o -d "`readlink breakpad`" \); then
+        AC_MSG_WARN([breakpad not compiled: breakpad package missing])
+      fi
+    fi
+
     AC_PATH_PROGS(DUMP_SYMS,dump_syms)
   fi
 fi
@@ -2616,7 +2733,14 @@ AC_ARG_ENABLE(
 dnl -------------- headers/functions/definitions/libraries -------------
 
 # set variables for tests
-AC_SET_TOOLCHAIN_SETTINGS($CC_FLAGS,$CXX_FLAGS,$CC_DEFINES,$CC_INCLUDES,$LD_FLAGS,$LIBRARY_PATHS,$STATIC_LIBRARIES,$LIBRARIES)
+AC_SET_TOOLCHAIN_SETTINGS($CC_FLAGS,
+                          $CXX_FLAGS,
+                          $CC_DEFINES,
+                          $CC_INCLUDES,
+                          $LD_FLAGS,
+                          $LIBRARY_PATHS,
+                          $STATIC_LIBRARIES,
+                          $LIBRARIES)
 
 # headers
 AC_CHECK_HEADERS(\
@@ -2660,6 +2784,7 @@ dnl echo -----------
 AC_CHECK_LARGEFILE_DEFINES
 AC_CHECK_SIZEOF(void *)
 
+AC_MSG_WARN([xxxhost=$host_os])
 AC_SEARCH_STATIC_LIBRARIES(uuid_generate,uuid,[STATIC_LIBRARIES="$STATIC_LIBRARIES uuid"],,uuid/uuid.h)
 case $host_os in
   linux*)
@@ -2682,7 +2807,14 @@ dnl AC_SEARCH_STATIC_LIBRARIES(zlibVersion,z,[HAVE_Z=1;STATIC_LIBRARIES="$STATIC
 dnl AC_MSG_ERROR([stop])
 
 # set variables for tests
-AC_SET_TOOLCHAIN_SETTINGS($CC_FLAGS,$CXX_FLAGS,$CC_DEFINES,$CC_INCLUDES,$LD_FLAGS,$LIBRARY_PATHS,$STATIC_LIBRARIES,$LIBRARIES)
+AC_SET_TOOLCHAIN_SETTINGS($CC_FLAGS,
+                          $CXX_FLAGS,
+                          $CC_DEFINES,
+                          $CC_INCLUDES,
+                          $LD_FLAGS,
+                          $LIBRARY_PATHS,
+                          $STATIC_LIBRARIES,
+                          $LIBRARIES)
 
 # check required defines
 AC_CHECK_PTHREAD_DEFINES
