added test for java, javac, jar, launch4j

diff --git a/bar/configure b/bar/configure
--- a/bar/configure
+++ b/bar/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=
 
 ac_unique_file="."
 ac_unique_file="bar.c"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_DIR INSTALL_BIN_DIR CONFIG_DIR TLS_DIR CC LD STRIP CC_FLAGS CC_WARN_FLAGS CC_OPTIMIZE CC_DEFINES CC_INCLUDES LD_FLAGS LIBRARY_PATHS LIBRARIES STATIC_LIBRARIES PERL INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_DIR INSTALL_BIN_DIR CONFIG_DIR TLS_DIR CC LD STRIP CC_FLAGS CC_WARN_FLAGS CC_OPTIMIZE CC_DEFINES CC_INCLUDES LD_FLAGS LIBRARY_PATHS LIBRARIES STATIC_LIBRARIES JAVA JAVAC JAR LAUNCH4J JAVA_FLAGS JAVAC_FLAGS SWT_DIR PERL INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -820,6 +820,9 @@ Optional Packages:
                           configuration directory (default: /etc/bar)
   --with-tls-dir=<path>   TLS/SLL configuration and certificate directory
                           (default: /etc/ssl)
+  --with-swt-dir=<path>   SWT directory
+  --with-launch4j=<program>
+                          launch4j program and parameters
 
 Some influential environment variables:
   CC          C compiler command
@@ -1372,6 +1375,16 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 
 
+
+
+
+
+
+
+
+
+
+
 CC_FLAGS=""
 CC_DEFINES=""
 CC_OPTIMIZE=""
@@ -1409,6 +1422,20 @@ if test "${with_tls_dir+set}" = set; then
   TLS_DIR=$withval
 else
   TLS_DIR=/etc/ssl
+
+fi;
+
+# Check whether --with-swt-dir or --without-swt-dir was given.
+if test "${with_swt_dir+set}" = set; then
+  withval="$with_swt_dir"
+  SWT_DIR=$withval
+
+fi;
+
+# Check whether --with-launch4j or --without-launch4j was given.
+if test "${with_launch4j+set}" = set; then
+  withval="$with_launch4j"
+  LAUNCH4J=$withval
 
 fi;
 
@@ -1744,6 +1771,191 @@ if test ! $ENABLE_LINK_DYNAMIC = "yes"; then
   LD_FLAGS="-static-libgcc"
 fi
 LIBRARY_PATHS="$LIBRARY_PATHS /usr/local/lib"
+
+for ac_prog in java
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAVA+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAVA in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAVA="$JAVA" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_JAVA="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+JAVA=$ac_cv_path_JAVA
+
+if test -n "$JAVA"; then
+  echo "$as_me:$LINENO: result: $JAVA" >&5
+echo "${ECHO_T}$JAVA" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$JAVA" && break
+done
+
+for ac_prog in javac
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAVAC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAVAC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAVAC="$JAVAC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_JAVAC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+JAVAC=$ac_cv_path_JAVAC
+
+if test -n "$JAVAC"; then
+  echo "$as_me:$LINENO: result: $JAVAC" >&5
+echo "${ECHO_T}$JAVAC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$JAVAC" && break
+done
+
+for ac_prog in jar
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAR+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAR in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAR="$JAR" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_JAR="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+JAR=$ac_cv_path_JAR
+
+if test -n "$JAR"; then
+  echo "$as_me:$LINENO: result: $JAR" >&5
+echo "${ECHO_T}$JAR" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$JAR" && break
+done
+
+for ac_prog in launch4j
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_LAUNCH4J+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $LAUNCH4J in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_LAUNCH4J="$LAUNCH4J" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_LAUNCH4J="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+LAUNCH4J=$ac_cv_path_LAUNCH4J
+
+if test -n "$LAUNCH4J"; then
+  echo "$as_me:$LINENO: result: $LAUNCH4J" >&5
+echo "${ECHO_T}$LAUNCH4J" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$LAUNCH4J" && break
+done
+
+
+JAVA_FLAGS=""
+if test "$ENABLE_DEBUG" = "yes"; then
+  JAVA_FLAGS="-enableassertions"
+fi
+if test "$ENABLE_DEBUG" = "yes"; then
+  JAVAC_FLAGS="-g"
+fi
 
 
 # set variables for tests
@@ -6082,6 +6294,22 @@ fi
   fi
 fi
 
+if test -z "$SWT_DIR"; then
+  echo "$as_me:$LINENO: checking for SWT" >&5
+echo $ECHO_N "checking for SWT... $ECHO_C" >&6
+  if   test -f /usr/local/swt/swt.jar; then
+    SWT_DIR=/usr/local/swt
+  elif test -f /usr/swt/swt.jar; then
+    SWT_DIR=/usr/swt
+  else
+    { { echo "$as_me:$LINENO: error: No swt.jar found. Please specify SWT directory with --with-swt-dir=<path>." >&5
+echo "$as_me: error: No swt.jar found. Please specify SWT directory with --with-swt-dir=<path>." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  echo "$as_me:$LINENO: result: $SWT_DIR" >&5
+echo "${ECHO_T}$SWT_DIR" >&6
+fi
+
 
 
 cat >>confdefs.h <<_ACEOF
@@ -6124,6 +6352,8 @@ else
 fi
 
           ac_config_files="$ac_config_files Makefile"
+
+          ac_config_files="$ac_config_files barcontrol/Makefile"
 
 
           ac_config_commands="$ac_config_commands TCL"
@@ -6679,6 +6909,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+  "barcontrol/Makefile" ) CONFIG_FILES="$CONFIG_FILES barcontrol/Makefile" ;;
   "TCL" ) CONFIG_COMMANDS="$CONFIG_COMMANDS TCL" ;;
   "BUILD_NOTE" ) CONFIG_COMMANDS="$CONFIG_COMMANDS BUILD_NOTE" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
@@ -6791,6 +7022,13 @@ s,@LD_FLAGS@,$LD_FLAGS,;t t
 s,@LIBRARY_PATHS@,$LIBRARY_PATHS,;t t
 s,@LIBRARIES@,$LIBRARIES,;t t
 s,@STATIC_LIBRARIES@,$STATIC_LIBRARIES,;t t
+s,@JAVA@,$JAVA,;t t
+s,@JAVAC@,$JAVAC,;t t
+s,@JAR@,$JAR,;t t
+s,@LAUNCH4J@,$LAUNCH4J,;t t
+s,@JAVA_FLAGS@,$JAVA_FLAGS,;t t
+s,@JAVAC_FLAGS@,$JAVAC_FLAGS,;t t
+s,@SWT_DIR@,$SWT_DIR,;t t
 s,@PERL@,$PERL,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
