added include config.h

diff --git a/bar/configure.in b/bar/configure.in
--- a/bar/configure.in
+++ b/bar/configure.in
@@ -1,7 +1,7 @@
 dnl --------------------------------------------------------------------
 dnl
 dnl $Source: /home/torsten/cvs/bar/configure.in,v $
-dnl $Revision: 1.2 $
+dnl $Revision: 1.3 $
 dnl $Author: torsten $
 dnl Contents: BAR auto-configure script (autoconf)
 dnl
@@ -41,13 +41,13 @@ AC_DEFUN([AC_CHECK_LARGEFILE_DEFINES],
 #include <stdio.h>
 #include <sys/types.h>
 #include <unistd.h>
-int main(void) { printf("%p",lseek64); return 0; }
+int main(void) { printf("%p",fseeko64); return 0; }
 EOF
       ${CC} ${CFLAGS} -Wall -Werror -c conftest.c -o conftest.o 1>/dev/null 2>/dev/null; rc=$?
       if test $rc -eq 0; then
         ac_largefile_defines=""
       else
-        ${CC} ${CFLAGS} -Wall -Werror -D_LARGEFILE64_SOURCE -c conftest.c -o conftest.o 1>/dev/null 2>/dev/null; rc=$?
+        ${CC} ${CFLAGS} -Wall -Werror -Dz_LARGEFILE64_SOURCE -c conftest.c -o conftest.o 1>/dev/null 2>/dev/null; rc=$?
         if test $rc -eq 0; then
           ac_largefile_defines="_LARGEFILE64_SOURCE"
         else
@@ -139,6 +139,7 @@ LIBRARIES=""
 STATIC_LIBRARIES=""
 
 ENABLE_DEBUG="no"
+ENABLE_LINK_STATIC="no"
 ENABLE_ZIP="yes"
 ENABLE_BZIP2="yes"
 ENABLE_GCRYPT="yes"
@@ -165,6 +166,11 @@ AC_ARG_ENABLE(
   debug,
   AC_HELP_STRING([--enable-debug],[enable debug version]),
   [ENABLE_DEBUG=$enableval]
+)
+AC_ARG_ENABLE(
+  link-static,
+  AC_HELP_STRING([--enable-link-static],[enable static linkage]),
+  [ENABLE_LINK_STATIC=$enableval]
 )
 AC_ARG_ENABLE(
   zip,
@@ -229,30 +235,53 @@ for z in $LIBRARY_PATHS ""; do
 done
 
 AC_C_LONG_LONG(AC_DEFINE(HAVE_LONG_LONG,1,[defined if long long data type available]),AC_MSG_ERROR(long long data type not available))
-dnl AC_SYS_LARGEFILE
-AC_CHECK_LARGEFILE_DEFINES
+AC_SYS_LARGEFILE
+dnl AC_CHECK_LARGEFILE_DEFINES
 AC_CHECK_PTHREAD_DEFINES
 
-#pthread_mutexattr_settype
+AC_CHECK_FUNCS(fseeko,,AC_ERROR([function fseeko() is not available]))
+AC_CHECK_FUNCS(ftello,,AC_ERROR([function ftello() is not available]))
 
-AC_SEARCH_LIBS(round,                  m,        ,AC_ERROR([n library not found]))
-AC_SEARCH_LIBS(pthread_create,         pthread,  ,AC_ERROR([pthread library not found]))
+AC_SEARCH_LIBS(round,m,,AC_ERROR([n library not found]))
+AC_SEARCH_LIBS(pthread_create,pthread,,AC_ERROR([pthread library not found]))
 if test $ENABLE_ZIP = "yes"; then
-  AC_SEARCH_LIBS(zlibVersion,            z,        [HAVE_Z=1;        LIBRARIES="$LIBRARIES z";        AC_DEFINE(HAVE_Z,        1,[z installed]        )])
+  if test $ENABLE_LINK_STATIC = "yes"; then
+    AC_SEARCH_LIBS(zlibVersion,z,[HAVE_Z=1;STATIC_LIBRARIES="$STATIC_LIBRARIES z";AC_DEFINE(HAVE_Z,1,[z installed])])
+  else
+    AC_SEARCH_LIBS(zlibVersion,z,[HAVE_Z=1;LIBRARIES="$LIBRARIES z";AC_DEFINE(HAVE_Z,1,[z installed])])
+  fi
 fi
 if test $ENABLE_BZIP2 = "yes"; then
-  AC_SEARCH_LIBS(BZ2_bzCompressInit,     bz2,      [HAVE_BZ2=1;      LIBRARIES="$LIBRARIES bz2";      AC_DEFINE(HAVE_BZ2,      1,[bzip2 installed]    )])
+  if test $ENABLE_LINK_STATIC = "yes"; then
+    AC_SEARCH_LIBS(BZ2_bzCompressInit,bz2,[HAVE_BZ2=1;STATIC_LIBRARIES="$STATIC_LIBRARIES bz2";AC_DEFINE(HAVE_BZ2,1,[bzip2 installed])])
+  else
+    AC_SEARCH_LIBS(BZ2_bzCompressInit,bz2,[HAVE_BZ2=1;LIBRARIES="$LIBRARIES bz2";AC_DEFINE(HAVE_BZ2,1,[bzip2 installed])])
+  fi
 fi
 if test $ENABLE_GCRYPT = "yes"; then
-  AC_SEARCH_LIBS(gcry_check_version,     gcrypt,   [HAVE_GCRYPT=1;   LIBRARIES="$LIBRARIES gcrypt";   AC_DEFINE(HAVE_GCRYPT,   1,[gcrypt installed]   )])
+  if test $ENABLE_LINK_STATIC = "yes"; then
+    AC_SEARCH_LIBS(gcry_check_version,gcrypt,[HAVE_GCRYPT=1;STATIC_LIBRARIES="$STATIC_LIBRARIES gcrypt crypto";AC_DEFINE(HAVE_GCRYPT,1,[gcrypt installed])])
+  else
+    AC_SEARCH_LIBS(gcry_check_version,gcrypt,[HAVE_GCRYPT=1;LIBRARIES="$LIBRARIES gcrypt crypto";AC_DEFINE(HAVE_GCRYPT,1,[gcrypt installed])])
+  fi
 fi
-AC_SEARCH_LIBS(gpg_strerror,           gpg-error,[HAVE_GPG_ERROR=1;LIBRARIES="$LIBRARIES gpg-error";AC_DEFINE(HAVE_GPG_ERROR,1,[GPG error installed])])
-AC_SEARCH_LIBS(libssh2_session_init_ex,ssh2,     [HAVE_SSH2=1;     LIBRARIES="$LIBRARIES ssh2";     AC_DEFINE(HAVE_SSH2,     1,[SSH2 installed]     )])
+if test $ENABLE_LINK_STATIC = "yes"; then
+  AC_SEARCH_LIBS(gpg_strerror,gpg-error,[HAVE_GPG_ERROR=1;STATIC_LIBRARIES="$STATIC_LIBRARIES gpg-error";AC_DEFINE(HAVE_GPG_ERROR,1,[GPG error installed])])
+else
+  AC_SEARCH_LIBS(gpg_strerror,gpg-error,[HAVE_GPG_ERROR=1;LIBRARIES="$LIBRARIES gpg-error";AC_DEFINE(HAVE_GPG_ERROR,1,[GPG error installed])])
+fi
+if test $ENABLE_LINK_STATIC = "yes"; then
+  AC_SEARCH_LIBS(libssh2_session_init_ex,ssh2,[HAVE_SSH2=1;STATIC_LIBRARIES="$STATIC_LIBRARIES ssh2";AC_DEFINE(HAVE_SSH2,1,[SSH2 installed])])
+else
+  AC_SEARCH_LIBS(libssh2_session_init_ex,ssh2,[HAVE_SSH2=1;LIBRARIES="$LIBRARIES ssh2";AC_DEFINE(HAVE_SSH2,1,[SSH2 installed])])
+fi
 if test $ENABLE_TLS = "yes"; then
-  AC_SEARCH_LIBS(gnutls_global_init,     gnutls,   [HAVE_GNU_TLS=1;  LIBRARIES="$LIBRARIES gnutls";   AC_DEFINE(HAVE_GNU_TLS,  1,[GNU TLS installed]  )])
+  if test $ENABLE_LINK_STATIC = "yes"; then
+    AC_SEARCH_LIBS(gnutls_global_init,gnutls,[HAVE_GNU_TLS=1;STATIC_LIBRARIES="$STATIC_LIBRARIES gnutls";AC_DEFINE(HAVE_GNU_TLS,1,[GNU TLS installed])])
+  else
+    AC_SEARCH_LIBS(gnutls_global_init,gnutls,[HAVE_GNU_TLS=1;LIBRARIES="$LIBRARIES gnutls";AC_DEFINE(HAVE_GNU_TLS,1,[GNU TLS installed])])
+  fi
 fi
-
-#pthread z bz2 gcrypt gpg-error ssh2 gnutls
 
 dnl -------------------------------- misc ------------------------------
 
